### ISSUE TITLE
MINOS errors via np_merrors() with fixed parameters

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/iminuit#479]
Hi, I am running into an issue when using `np_merrors()` with fixed parameters:

```python
import iminuit

def f(x):
    return x[0]**2 + 0.5*x[1]**2

m = iminuit.Minuit.from_array_func(
        f,
        [1.0, 1.0],
        error = [0.0, 0.1],
        fix=[True, False],
        name=["a", "b"],
        errordef=1,
    )
m.migrad()
m.minos(var="b")
print(m.merrors)
print(m.np_merrors())
```

results in

```
------------------------------------
|          |           b           |
------------------------------------
|  Error   |   -1.4    |    1.4    |
|  Valid   |   True    |   True    |
| At Limit |   False   |   False   |
| Max FCN  |   False   |   False   |
| New Min  |   False   |   False   |
------------------------------------
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    print(m.np_merrors())
  File "src/iminuit/_libiminuit.pyx", line 1150, in iminuit._libiminuit.Minuit.np_merrors
  File "[...]/lib/python3.8/site-packages/iminuit/util.py", line 257, in __getitem__
    v = super(MErrors, self).__getitem__(key)
KeyError: 'a'
```

I am using `iminuit` 1.4.9. This issue might be related to #459.

**Comment by HDembinski** [comment]
Thank you for reporting this and the minimal example to reproduce.

**Comment by alexander-held** [comment]
Thank you for the quick fix!
