### ISSUE TITLE
error with Veusz

### ISSUE THREAD

**Issue by aman-upadhyay** [scikit-hep/iminuit#615]
I am using veusz and built python-iminuit from AUR. I can not fit anything as this error pops up.   

61 2.41166e+21 7.72541e-07 1.62654e-12 
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/veusz/windows/consolewindow.py", line 258, in runFunction
    func()
  File "/usr/lib/python3.9/site-packages/veusz/widgets/fit.py", line 341, in actionFit
    vals, chi2, dof = minuitFit(
  File "/usr/lib/python3.9/site-packages/veusz/widgets/fit.py", line 99, in minuitFit
    print(_('Fit results:\n') + "\n".join([
  File "/usr/lib/python3.9/site-packages/veusz/widgets/fit.py", line 101, in <listcomp>
    % (n, m.values[n], m.errors[n], m.merrors[(n, 1.0)],
  File "/usr/lib/python3.9/site-packages/iminuit/util.py", line 759, in __getitem__
    return OrderedDict.__getitem__(self, key)
KeyError: ('a', 1.0)

**Comment by mayou36** [comment]
Do you maybe have a simple example to reproduce the issue? It seems to be caused by the call `m.merrors[(n, 1.0)]`, are you sure that `(n, 1.0)` is the parameter name? I think this should only be 'a' (resp. `n`)

**Comment by HDembinski** [comment]
The API for merrors changed in the 2.x series, veusz needs to update the call.

**Comment by aman-upadhyay** [comment]
Thanks a lot!
