### ISSUE TITLE
Cannot redirect output to text file

### ISSUE THREAD

**Issue by Beliavsky** [scikit-hep/iminuit#885]
On Windows, in Terminal, I can run the program

```
from iminuit import Minuit

def cost_function(x, y, z):
    return (x - 2) ** 2 + (y - 3) ** 2 + (z - 4) ** 2

m = Minuit(cost_function, x=0, y=0, z=0)
m.migrad()  # run optimiser
m.hesse()   # run covariance estimator
print(str(m))
```
and send the output to the screen, but when I try to send it to a text file such as temp.txt I get an error 

```
Traceback (most recent call last):
  File "c:\Users\myname\OneDrive - Solum Partners LP\Documents\python\xxminuit.py", line 9, in <module>
    print(str(m))
  File "c:\Users\myname\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-74: character maps to <undefined>
```

**Comment by HDembinski** [comment]
You are having a general unicode issue on Windows and iminuit uses unicode a lot. Your solution is given here:
https://stackoverflow.com/questions/42070668/python-3-default-encoding-cp1252
